services:
    caddy:
        # image: caddy:2.11-alpine
        build: .
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
            - '443:443/udp'
        # volumes:
        #     # - ./caddy:/etc/caddy
        #     # - ./dist:/srv
        #     - ./caddy/caddy_persist/data:/data
        #     - ./caddy/caddy_persist/config:/config

volumes:
    caddy_data:
    caddy_config:
